---
kind: pipeline
type: docker
name: default
steps:
- name: test
  image: node:21-alpine3.18
  commands:
  - corepack enable
  - pnpm i --frozen-lockfile --strict-peer-dependencies
trigger:
  event:
    - push
